### ISSUE TITLE
[TECH ED] <Prepare for live session #277 >

### ISSUE THREAD

**Issue by fhkahin** [CodeYourFuture/Module-Servers#167]
### Link to the coursework

https://curriculum.codeyourfuture.io/node/sprints/2/prep/

### Why are we doing this?

The URL link associated with the [TECH ED] Prepare for live session is currently dysfunctional, displaying a '404 Page not found' error upon clicking. Could someone please rectify this issue ?

### Maximum time in hours

05 minutes

### How to get help

The URL link associated with the [[TECH ED] Prepare for live session](https://curriculum.codeyourfuture.io/node/sprints/2/prep/) is currently dysfunctional, displaying a '404 Page not found' error upon clicking. Could someone please rectify this issue ?

### How to submit

N/A

### How to review

N/A

### Anything else?

N/a

**Comment by SallyMcGrath** [comment]
Cheers, I'll fix it now
